### ISSUE TITLE
AttributeError: 'XGBModel' object has no attribute 'enable_categorical'

### ISSUE THREAD

**Issue by ceyhanmolla** [Kenny1941/Crypto_Bot#4]
<bound method Client.get_open_orders of <binance.client.Client object at 0x7f78442fb3d0>>
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.23.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.23.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LabelBinarizer from version 0.23.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator MLPClassifier from version 0.23.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
Traceback (most recent call last):
  File "Crypto_Bot_Class.py", line 529, in <module>
    obs_3, reward_3, info_3=env_3.step()
  File "Crypto_Bot_Class.py", line 276, in step
    next_state=self.action()
  File "Crypto_Bot_Class.py", line 315, in action
    act=self.get_act()
  File "Crypto_Bot_Class.py", line 364, in get_act
    predict=self.model.predict_proba(row)[0,1]
  File "/usr/local/lib/python3.8/dist-packages/xgboost/sklearn.py", line 1348, in predict_proba
    class_probs = super().predict(
  File "/usr/local/lib/python3.8/dist-packages/xgboost/sklearn.py", line 879, in predict
    if self._can_use_inplace_predict():
  File "/usr/local/lib/python3.8/dist-packages/xgboost/sklearn.py", line 811, in _can_use_inplace_predict
    predictor = self.get_params().get("predictor", None)
  File "/usr/local/lib/python3.8/dist-packages/xgboost/sklearn.py", line 505, in get_params
    params.update(cp.__class__.get_params(cp, deep))
  File "/usr/local/lib/python3.8/dist-packages/xgboost/sklearn.py", line 502, in get_params
    params = super().get_params(deep)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 210, in get_params
    value = getattr(self, key)
AttributeError: 'XGBModel' object has no attribute 'enable_categorical'

**Comment by Kenny1941** [comment]
XGBoost was having dependency issues for several people, so I decided to eliminate the XGBModel and added another Neural Network instead (Big_NN_Model_2). If you want to work with the version you have now, I would try adding

row=np.array(row)
directly above: 
predict=self.model.predict_proba(row)[0,1]

in the XGBModel Class. But it's a little hard for me to tell since I don't get that error.


The fitted feature name warning should now be resolved.


The unpickle warning is because I constructed the models on an older version of sklearn. I will update the models using the newest version of sklearn in the near future, but I don't think that should cause any immediate issues. 

Thank you for bringing these to my attention!
